import monitorOne from "../../assets/11zon_compressed/monitor1_7_11zon.jpg"
import monitorTwo from "../../assets/11zon_compressed/monitor2_8_11zon.jpg"
import monitorThre from "../../assets/11zon_compressed/monitor3_9_11zon.jpg"
import lampiOne from "../../assets/11zon_compressed/lampi1_4_11zon.jpg"
import lampiTwo from "../../assets/11zon_compressed/lampi2_5_11zon.jpg"
import lampiThre from "../../assets/11zon_compressed/lampi3_6_11zon.jpg"
import krovatOne from "../../assets/11zon_compressed/krovat1_1_11zon.jpg"
import krovatTwo from "../../assets/11zon_compressed/krovat2_2_11zon.jpg"
import krovatThre from "../../assets/11zon_compressed/krovat3_3_11zon.jpg"
import rentgenOne from "../../assets/11zon_compressed/rentgen1_10_11zon.jpg"
import rentgenTwo from "../../assets/11zon_compressed/rentgen2_11_11zon.jpg"
import rentgenThre from "../../assets/11zon_compressed/rentgen3_12_11zon.jpg"


export const catalogCrData = [
    {
        id: 1,
        img: "https://global-mt.ru/upload/iblock/b43/1isi80490zvej6oyamc3gsylgdftzeyw/10k11.png",
        title: "-30%",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "999 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213596134",
        naliche: "В наличии",
        kategory: "Группы товаров",
    },
    {
        id: 2,
        img: "https://global-mt.ru/upload/iblock/0cc/z5ewycempc7q5y0ndz0ydmmyn6n6ljwm.jpg",
        title: "Хит продаж",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "112 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "21313156634",
        naliche: "В наличии",
    },
    {
        id: 3,
        img: "https://global-mt.ru/upload/iblock/208/2pphr5vxq0jjz4gk7ofhwe0hwwret6p4.jpg",
        title: "Новинка",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "240 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213139864",
        naliche: "В наличии",
    },
    {
        id: 4,
        img: "https://global-mt.ru/upload/iblock/99c/f4culrnhumf342o2d1hcx4sc77hn2a6z.jpg",
        title: "Новинка",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "320 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "211353134",
        naliche: "В наличии",
    },
    {
        id: 5,
        img: monitorOne,
        title: "-30%",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "1 390 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "2131356434",
        naliche: "В наличии",
        kategory: "Мониторы",
    },
    {
        id: 6,
        img: lampiOne,
        title: "-30%",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "30 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "2131345434",
        naliche: "В наличии",
        kategory: "Лампы",
    },
    {
        id: 7,
        img: "https://global-mt.ru/upload/iblock/2b9/fxww4q10pv3293p89z5ih8airw4swkix.jpg",
        title: "Новинка",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "309 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "983526",
        naliche: "В наличии",
    },
    {
        id: 8,
        img: "https://global-mt.ru/upload/iblock/b43/1isi80490zvej6oyamc3gsylgdftzeyw/10k11.png",
        title: "Новинка",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "180 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213234",
        naliche: "В наличии",
    },
    {
        id: 9,
        img: krovatOne,
        title: "-30%",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "350 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213112",
        naliche: "В наличии",
        kategory: "Кровати",
    },
    {
        id: 10,
        img: "https://global-mt.ru/upload/iblock/41c/hxs1u8ffexah6jibieebhrw0h4d7ka13.png",
        title: "Новинка",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "350 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213112",
        naliche: "В наличии",
    },
    {
        id: 11,
        img: rentgenOne,
        title: "-30%",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "350 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213112",
        naliche: "В наличии",
        kategory: "Рентгены",
    },
    {
        id: 12,
        img: "https://global-mt.ru/upload/iblock/41c/hxs1u8ffexah6jibieebhrw0h4d7ka13.png",
        title: "Хит продаж",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "350 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213112",
        naliche: "В наличии",

    },
    {
        id: 13,
        img: "https://global-mt.ru/upload/iblock/41c/hxs1u8ffexah6jibieebhrw0h4d7ka13.png",
        title: "-30%",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "350 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213112",
        naliche: "В наличии",
        kategory: "Группы товаров",
    },
    {
        id: 14,
        img: "https://global-mt.ru/upload/iblock/41c/hxs1u8ffexah6jibieebhrw0h4d7ka13.png",
        title: "Хит продаж",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "350 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213112",
        naliche: "В наличии",
    },
    {
        id: 15,
        img: "https://global-mt.ru/upload/iblock/41c/hxs1u8ffexah6jibieebhrw0h4d7ka13.png",
        title: "-30%",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "350 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213112",
        naliche: "В наличии",
        kategory: "Группы товаров",
    },
    {
        id: 16,
        img: "https://global-mt.ru/upload/iblock/41c/hxs1u8ffexah6jibieebhrw0h4d7ka13.png",
        title: "Новинка",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "350 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213112",
        naliche: "В наличии",
    },
    {
        id: 17,
        img: "https://global-mt.ru/upload/iblock/41c/hxs1u8ffexah6jibieebhrw0h4d7ka13.png",
        title: "Новинка",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "350 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213112",
        naliche: "В наличии",

    },
    {
        id: 18,
        img: "https://global-mt.ru/upload/iblock/41c/hxs1u8ffexah6jibieebhrw0h4d7ka13.png",
        title: "Новинка",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "350 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213112",
        naliche: "В наличии",
    },
    {
        id: 19,
        img: monitorThre,
        title: "-30%",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "350 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213112",
        naliche: "В наличии",
        kategory: "Мониторы",
    },
    {
        id: 20,
        img: "https://global-mt.ru/upload/iblock/41c/hxs1u8ffexah6jibieebhrw0h4d7ka13.png",
        title: "Новинка",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "350 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213112",
        naliche: "В наличии",

    },
    {
        id: 21,
        img: "https://global-mt.ru/upload/iblock/41c/hxs1u8ffexah6jibieebhrw0h4d7ka13.png",
        title: "Новинка",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "350 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213112",
        naliche: "В наличии",
    },
    {
        id: 22,
        img: "https://global-mt.ru/upload/iblock/41c/hxs1u8ffexah6jibieebhrw0h4d7ka13.png",
        title: "Новинка",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "350 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213112",
        naliche: "В наличии",
    },
    {
        id: 23,
        img: "https://global-mt.ru/upload/iblock/41c/hxs1u8ffexah6jibieebhrw0h4d7ka13.png",
        title: "Новинка",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "350 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213112",
        naliche: "В наличии",
    },
    {
        id: 24,
        img: "https://global-mt.ru/upload/iblock/41c/hxs1u8ffexah6jibieebhrw0h4d7ka13.png",
        title: "Хит продаж",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "350 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213112",
        naliche: "В наличии",
    },
    {
        id: 25,
        img: lampiThre,
        title: "-30%",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "350 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213112",
        naliche: "В наличии",
        kategory: "Лампы",
    },
    {
        id: 26,
        img: "https://global-mt.ru/upload/iblock/41c/hxs1u8ffexah6jibieebhrw0h4d7ka13.png",
        title: "Хит продаж",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "350 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213112",
        naliche: "В наличии",
    },
    {
        id: 27,
        img: "https://global-mt.ru/upload/iblock/41c/hxs1u8ffexah6jibieebhrw0h4d7ka13.png",
        title: "Хит продаж",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "350 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213112",
        naliche: "В наличии",
    },
    {
        id: 28,
        img: "https://global-mt.ru/upload/iblock/41c/hxs1u8ffexah6jibieebhrw0h4d7ka13.png",
        title: "Новинка",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "350 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213112",
        naliche: "В наличии",
    },
    {
        id: 29,
        img: "https://global-mt.ru/upload/iblock/41c/hxs1u8ffexah6jibieebhrw0h4d7ka13.png",
        title: "Хит продаж",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "350 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213112",
        naliche: "В наличии",
    },
    {
        id: 30,
        img: krovatThre,
        title: "-30%",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "350 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213112",
        naliche: "В наличии",
        kategory: "Кровати",
    },
    {
        id: 31,
        img: rentgenThre,
        title: "-30%",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "350 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213112",
        naliche: "В наличии",
        kategory: "Рентгены",
    },
    {
        id: 32,
        img: "https://global-mt.ru/upload/iblock/41c/hxs1u8ffexah6jibieebhrw0h4d7ka13.png",
        title: "-30%",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "350 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213112",
        naliche: "В наличии",
        kategory: "Группы товаров",
    },
    {
        id: 33,
        img: "https://global-mt.ru/upload/iblock/41c/hxs1u8ffexah6jibieebhrw0h4d7ka13.png",
        title: "-30%",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "350 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213112",
        naliche: "В наличии",
        kategory: "Группы товаров",
    },
    {
        id: 34,
        img: monitorTwo,
        title: "-30%",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "350 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213112",
        naliche: "В наличии",
        kategory: "Мониторы",
    },
    {
        id: 35,
        img: lampiTwo,
        title: "-30%",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "112 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "21313156634",
        naliche: "В наличии",
        kategory: "Лампы",
    },
    {
        id: 36,
        img: krovatTwo,
        title: "-30%",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "240 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "213139864",
        naliche: "В наличии",
        kategory: "Кровати",
    },
    {
        id: 37,
        img:rentgenTwo,
        title: "-30%",
        name: "Рото-носовая маска Sleepnet Veraseal 2",
        common_name: "Артикул: 213134",
        price_title: "В наличии",
        price: "320 000 руб.",
        btn_name: "Добавить в корзину",
        kategoria: "Лабораторное оборудование",
        Manufacturer: "Lorem",
        vendorcode: "211353134",
        naliche: "В наличии",
        kategory: "Рентгены",
    },
]