export const Data = [
    {
        id: 1,
        img: "https://global-mt.ru/upload/iblock/feb/2wjqdpi5utb8m2mh3f8kjnzz9s18hb4w/AGAT.png",
        common_name: "Поставка медицинского оборудования ",
        title_name: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ",
        bg_title: "Запросить цену",
        wh_title: "В каталог",
    },
    {
        id: 2,
        img: "https://global-mt.ru/upload/iblock/1e0/xhm58vzjel3b8j2793v3bnrfwtni23x8/fibro.png",
        common_name: "Поставка медицинского оборудования ",
        title_name: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ",
        bg_title: "Запросить цену",
        wh_title: "В каталог",
    },
    {
        id: 3,
        img: "https://global-mt.ru/upload/iblock/30c/2jvhgybdr6b0aj76dvm49k2ft5top4xw/gmt_na_glavnuyu2_.png",
        common_name: "Поставка медицинского оборудования ",
        title_name: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ",
        bg_title: "Запросить цену",
        wh_title: "В каталог",
    },
    {
        id: 4,
        img: "https://global-mt.ru/upload/iblock/feb/2wjqdpi5utb8m2mh3f8kjnzz9s18hb4w/AGAT.png",
        common_name: "Поставка медицинского оборудования ",
        title_name: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ",
        bg_title: "Запросить цену",
        wh_title: "В каталог",
    },
    {
        id: 5,
        img: "https://global-mt.ru/upload/iblock/1e0/xhm58vzjel3b8j2793v3bnrfwtni23x8/fibro.png",
        common_name: "Поставка медицинского оборудования",
        title_name: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ",
        bg_title: "Запросить цену",
        wh_title: "В каталог",
    },
    {
        id: 6,
        img: "https://global-mt.ru/upload/iblock/30c/2jvhgybdr6b0aj76dvm49k2ft5top4xw/gmt_na_glavnuyu2_.png",
        common_name: "Поставка медицинского оборудования",
        title_name: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ",
        bg_title: "Запросить цену",
        wh_title: "В каталог",
    },
]