import dataimg from '../../assets/dataImg.png'

export const upravlenie = [
    {
        id: 1,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Австралия",
    },
    {
        id: 2,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Австрия",
    },
    {
        id: 3,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Беларусь",
    },
    {
        id: 4,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Бельгия",
    },
    {
        id: 5,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Великобритания",
    },
    {
        id: 6,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Германия",
    },
    {
        id: 7,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Израиль",
    },
    {
        id: 8,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Испания",
    },
    {
        id: 9,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Австралия",
    },
    {
        id: 10,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Австрия",
    },
    {
        id: 11,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Беларусь",
    },
    {
        id: 12,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Бельгия",
    },
    {
        id: 13,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Великобритания",
    },
    {
        id: 14,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Германия",
    },
    {
        id: 15,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Израиль",
    },
    {
        id: 16,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Испания",
    },
    {
        id: 17,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Австралия",
    },
    {
        id: 18,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Австрия",
    },
    {
        id: 19,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Беларусь",
    },
    {
        id: 20,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Бельгия",
    },
    {
        id: 21,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Великобритания",
    },
    {
        id: 22,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Германия",
    },
    {
        id: 23,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Израиль",
    },
    {
        id: 24,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Испания",
    },
    {
        id: 25,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Австралия",
    },
    {
        id: 26,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Австрия",
    },
    {
        id: 27,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Беларусь",
    },
    {
        id: 28,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Бельгия",
    },
    {
        id: 29,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Великобритания",
    },
    {
        id: 30,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Германия",
    },
    {
        id: 31,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Израиль",
    },
    {
        id: 32,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Испания",
    },
    {
        id: 33,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Австралия",
    },
    {
        id: 34,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Австрия",
    },
    {
        id: 35,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Беларусь",
    },
    {
        id: 36,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Бельгия",
    },
    {
        id: 37,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Великобритания",
    },
    {
        id: 38,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Германия",
    },
    {
        id: 39,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Израиль",
    },
    {
        id: 40,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Испания",
    },
    {
        id: 41,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Австралия",
    },
    {
        id: 42,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Австрия",
    },
    {
        id: 43,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Беларусь",
    },
    {
        id: 44,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Бельгия",
    },
    {
        id: 45,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Великобритания",
    },
    {
        id: 46,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Германия",
    },
    {
        id: 47,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Израиль",
    },
    {
        id: 48,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Испания",
    },
    {
        id: 49,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Австралия",
    },
    {
        id: 50,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Австрия",
    },
    {
        id: 51,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Беларусь",
    },
    {
        id: 52,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Бельгия",
    },
    {
        id: 53,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Великобритания",
    },
    {
        id: 54,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Германия",
    },
    {
        id: 55,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Израиль",
    },
    {
        id: 56,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Испания",
    },
    {
        id: 57,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Австралия",
    },
    {
        id: 58,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Австрия",
    },
    {
        id: 59,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Беларусь",
    },
    {
        id: 60,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Бельгия",
    },
    {
        id: 61,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Великобритания",
    },
    {
        id: 62,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Германия",
    },
    {
        id: 63,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Израиль",
    },
    {
        id: 64,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Испания",
    },
    {
        id: 65,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Австралия",
    },
    {
        id: 66,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Австрия",
    },
    {
        id: 67,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Беларусь",
    },
    {
        id: 68,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Бельгия",
    },
    {
        id: 69,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Великобритания",
    },
    {
        id: 70,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Германия",
    },
    {
        id: 71,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Израиль",
    },
    {
        id: 72,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Испания",
    },
    {
        id: 73,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Австралия",
    },
    {
        id: 74,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Австрия",
    },
    {
        id: 75,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Беларусь",
    },
    {
        id: 76,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Бельгия",
    },
    {
        id: 77,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Великобритания",
    },
    {
        id: 78,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Германия",
    },
    {
        id: 79,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Израиль",
    },
    {
        id: 80,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Испания",
    },
    {
        id: 81,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Австралия",
    },
    {
        id: 82,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Австрия",
    },
    {
        id: 83,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Беларусь",
    },
    {
        id: 84,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Бельгия",
    },
    {
        id: 85,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Великобритания",
    },
    {
        id: 86,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Германия",
    },
    {
        id: 87,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Израиль",
    },
    {
        id: 88,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Испания",
    },
    {
        id: 89,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Австралия",
    },
    {
        id: 90,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Австрия",
    },
    {
        id: 91,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Беларусь",
    },
    {
        id: 92,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Бельгия",
    },
    {
        id: 93,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Великобритания",
    },
    {
        id: 94,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Германия",
    },
    {
        id: 95,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Израиль",
    },
    {
        id: 96,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Испания",
    },
    {
        id: 97,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Австралия",
    },
    {
        id: 98,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Австрия",
    },
    {
        id: 99,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Беларусь",
    },
    {
        id: 100,
        img: dataimg,
        text: "НМИЦ онкологии им. Н.Н. Блохина",
        country: "Бельгия",
    },
];
